apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-dep
  annotations:
    kubernetes.io/change-cause: update to v2, ngx=1.22

spec:
  minReadySeconds: 15      # 确认Pod就绪的等待时间
  replicas: 4
  selector:
    matchLabels:
      app: ngx-dep

  template:
    metadata:
      labels:
        app: ngx-dep
    spec:
      containers:
      - image: nginx:1.22-alpine
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ngx-conf-vol
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: ngx-conf-vol
          configMap:
            name: ngx-conf
            items: #路径映射，不配置则默认映射(key->key)
              - key: default.conf
                path: default.conf
#              - key: default2 #别名
#                path: def2222
#              - key: default2
#                path: def33333

