
#  docker-compose -f wp-compose.yml up -d
#  docker-compose -f wp-compose.yml ps
#  docker-compose exec 来进入容器内部
#  docker-compose -f wp-compose.yml exec -it nginx sh
#  docker-compose -f wp-compose.yml down#  docker-compose -f reg-compose.yml ps

version: '3'
services:

  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: always

    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: wp
      MARIADB_PASSWORD: 123
      MARIADB_ROOT_PASSWORD: 123

#      docker run -d --rm \
#      --env MARIADB_DATABASE=db \
#      --env MARIADB_USER=wp \
#      --env MARIADB_PASSWORD=123 \
#      --env MARIADB_ROOT_PASSWORD=123 \
#      mariadb:10

  wordpress:
    image: wordpress:5
    container_name: wordpress
    restart: always

    environment:
      WORDPRESS_DB_HOST: mariadb  #注意这里，数据库的网络标识
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: db
    #depends_on，它用来设置容器的依赖关系，指定容器启动的先后顺序
    depends_on:
      - mariadb

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wp.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - wordpress
