apiVersion: v1
kind: Pod
metadata:
  name: ngx-pod-probe

spec:
  volumes:
    - name: ngx-conf-vol
      configMap:
        name: ngx-probe-conf

  containers:
    - image: nginx:alpine
      name: ngx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: ngx-conf-vol

      startupProbe:
        periodSeconds: 1
        exec:
          command: ["cat", "/var/run/nginx.pid"]
#          command: ["cat", "nginx.pid"] #错误的文件

      livenessProbe:
        periodSeconds: 10
        tcpSocket:
          port: 80
#          port: 8080 #错误的端口号

      readinessProbe:
        periodSeconds: 5
        httpGet:
          path: /ready
          port: 80
#          port: 8080 #错误的端口号

# 配置
# periodSeconds，执行探测动作的时间间隔，默认是 10 秒探测一次。
# timeoutSeconds，探测动作的超时时间，如果超时就认为探测失败，默认是 1 秒。
# successThreshold，连续几次探测成功才认为是正常，对于 startupProbe 和 livenessProbe 来说它只能是 1。
# failureThreshold，连续探测失败几次才认为是真正发生了异常，默认是 3 次。

#  探测方式， Kubernetes 支持 3 种：
#  exec，执行一个 Linux 命令，比如 ps、cat 等等，和 container 的 command 字段很类似。
#  tcpSocket，使用 TCP 协议尝试连接容器的指定端口。
#  httpGet，连接端口并发送 HTTP GET 请求。
