apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev-ns

spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 50Mi
      default:
        cpu: 500m
        memory: 100Mi
    - type: Pod
      max:
        cpu: 800m
        memory: 200Mi





# 你可以用命令 kubectl explain limits 来查看它的 YAML 字段详细说明，这里说几个要点：
#        * spec.limits 是它的核心属性，描述了默认的资源限制。
#        * type 是要限制的对象类型，可以是 Container、Pod、PersistentVolumeClaim。
#        * default 是默认的资源上限，对应容器里的 resources.limits，只适用于 Container。
#        * defaultRequest 默认申请的资源，对应容器里的 resources.requests，同样也只适用于 Container。
#        * max、min 是对象能使用的资源的最大最小值。

#  它设置了每个容器默认申请 0.2 的 CPU 和 50MB 内存，
#  容器的资源上限是 0.5 的 CPU 和 100MB 内存，
#  每个 Pod 的最大使用量是 0.8 的 CPU 和 200MB 内存。